# Generated by Django 4.0.4 on 2022-04-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_moderatorinvitaion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorinvitaion',
            name='accepted',
        ),
        migrations.AddField(
            model_name='moderatorinvitaion',
            name='status',
            field=models.CharField(default='INVIATION_STATUS_PENDING', max_length=255),
        ),
    ]
