# Generated by Django 4.0.4 on 2022-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_moderatorinvitaion_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitaion',
            name='status',
            field=models.CharField(choices=[('INVIATION_STATUS_ACCETPED', 'INVIATION_STATUS_ACCETPED'), ('INVIATION_STATUS_DECLINED', 'INVIATION_STATUS_DECLINED'), ('INVIATION_STATUS_PENDING', 'INVIATION_STATUS_PENDING')], default='INVIATION_STATUS_PENDING', max_length=255),
        ),
    ]
